clear all
close all


c_light = 2.99792458e+8; % light velocity, m/s
H = 6.626070040e-34; % Planck constant, J*s
HBAR = 1.054D-34; % reduced Planck constant, J*s
kB = 1.3806488e-23; % Boltzmann constant, J/K
Q = 1.6021766208e-19; % elementary charge, C
T = 300; % temperature, K
eps0 = 8.854D-12; % vacuum permittivity constant, F/m
M0 = 9.1095D-31; % electron mass, kg
%
rho = 5320; % mass density, kg/m?3
eps_s = 12.9*eps0; % static dielectric constant, F/m
eps_infty = 10.9*eps0; % high-frequency dielectric constant, F/m
v_l = 5240; % longitudinal sound velocity, m/s
meff = 0.067*M0; % effective mass, kg
alpha = 0.64/Q; % nonparabolicity factor, 1/J
hwpop = 0.0354*Q; % longitudinal optical phonon energy, J
Daco = 7*Q; % acoustic deformation potential, J
egap = 1.424*Q; % energy gap, J

B = [-1/2 1/6 0 -1/30 0 1/42 0 -1/30 0 5/66]; % Bernoulli numbers
% generated by bernoulli(sym(1:10))
z = sym('z','real');
x = sym('x','real');
nphon = 1/z - 1/2;
m=1; nphon = nphon + B(2*m)*z^(2*m-1)/factorial(2*m);
m=2; nphon = nphon + B(2*m)*z^(2*m-1)/factorial(2*m);
m=3; nphon = nphon + B(2*m)*z^(2*m-1)/factorial(2*m);
m=4; nphon = nphon + B(2*m)*z^(2*m-1)/factorial(2*m);
m=5; nphon = nphon + B(2*m)*z^(2*m-1)/factorial(2*m);
%
F1 = int(nphon*z^2,0,x);
F2 = int(nphon*z^3,0,x);
G1 = int((nphon+1)*z^2,0,x);
G2 = int((nphon+1)*z^3,0,x);